availableSecrets:
  secretManager:
  - env: BOT_TOKEN
    versionName: projects/${PROJECT_ID}/secrets/BOT_TOKEN/versions/latest
options:
  logging: CLOUD_LOGGING_ONLY
steps:
- args:
  - ci
  entrypoint: npm
  id: Install dependencies
  name: node:18
- args:
  - tests/environment_check.js
  entrypoint: node
  id: Environment check
  name: node:18
- args:
  - run
  - test:unit
  - --
  - --detectOpenHandles
  - --forceExit
  entrypoint: npm
  env:
  - NODE_ENV=test
  id: Run unit tests
  name: node:18
- args:
  - run
  - test:integration
  - --
  - --detectOpenHandles
  - --forceExit
  - --verbose
  entrypoint: npm
  env:
  - NODE_ENV=test
  - DEBUG=true
  id: Run integration tests
  name: node:18
  timeout: 900s
- args:
  - run
  - test:verification
  - --
  - --detectOpenHandles
  - --forceExit
  entrypoint: npm
  env:
  - NODE_ENV=test
  id: Run verification tests
  name: node:18
- args:
  - functions
  - deploy
  - telegram-bot
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=nodejs20
  - --entry-point=bot
  - --service-account=${_SERVICE_ACCOUNT}
  - --set-env-vars=BOT_TOKEN=${_BOT_TOKEN},GOOGLE_CLOUD_PROJECT=${PROJECT_ID},BIGQUERY_DATASET_ID=${_BIGQUERY_DATASET_ID}
  - --gen2
  - --allow-unauthenticated
  entrypoint: gcloud
  id: Deploy to Cloud Functions
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  secretEnv:
  - BOT_TOKEN
substitutions:
  _BIGQUERY_DATASET_ID: business_operations
  _SERVICE_ACCOUNT: your-service-account@${PROJECT_ID}.iam.gserviceaccount.com
timeout: 1800s
