options:
  logging: CLOUD_LOGGING_ONLY
steps:
- args:
  - ci
  entrypoint: npm
  id: Install dependencies
  name: node:20
- args:
  - tests/environment_check.js
  entrypoint: node
  id: Environment check
  name: node:20
- args:
  - run
  - test:unit
  - --
  - --detectOpenHandles
  - --forceExit
  entrypoint: npm
  env:
  - NODE_ENV=test
  id: Run unit tests
  name: node:20
- args:
  - run
  - test:integration
  - --
  - --detectOpenHandles
  - --forceExit
  - --verbose
  entrypoint: npm
  env:
  - NODE_ENV=test
  - DEBUG=true
  id: Run integration tests
  name: node:20
  timeout: 900s
- args:
  - run
  - test:verification
  - --
  - --detectOpenHandles
  - --forceExit
  entrypoint: npm
  env:
  - NODE_ENV=test
  id: Run verification tests
  name: node:20
- args:
  - functions
  - deploy
  - telegram-bot
  - --runtime=nodejs20
  - --region=us-central1
  - --source=.
  - --entry-point=bot
  - --trigger-http
  - --allow-unauthenticated
  - --service-account=telegram-bot-project-470513@appspot.gserviceaccount.com
  - --memory=256MB
  - --timeout=30s
  - --set-env-vars=NODE_ENV=production
  entrypoint: gcloud
  id: Deploy to Cloud Functions
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  timeout: 1200s
substitutions:
  _BIGQUERY_DATASET_ID: business_operations
  _SERVICE_ACCOUNT: your-service-account@${PROJECT_ID}.iam.gserviceaccount.com
timeout: 1800s
