name: CI/CD Pipeline
true:
  pull_request:
    branches:
    - main
    - dev
  push:
    branches:
    - main
    - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests with mocking
      run: 'echo "Running unit tests with proper mocking..."

        npm run test:unit

        '
    - name: Run integration tests with mocking
      run: 'echo "Running integration tests with proper mocking..."

        npm run test:integration

        '
    - name: Run verification tests
      run: 'echo "Running verification tests..."

        npm run test:verification'
    strategy:
      matrix:
        node-version:
        - 20.x
