name: Usage Capacity Test
true:
  schedule:
  - cron: 0 6 * * 1
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install pytz

        '
    - name: Run usage test
      run: python mock_usage_test.py
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: usage-test-results
        path: test_results/
    - if: failure()
      name: Create issue if quotas exceeded
      uses: actions/github-script@v6
      with:
        script: "github.rest.issues.create({\n  owner: context.repo.owner,\n  repo:\
          \ context.repo.repo,\n  title: '?? Usage Quota Alert',\n  body: 'Automated\
          \ test detected potential quota exceedance. Check test results for details.',\n\
          \  labels: ['quota', 'urgent']\n})\n"
