# .github/workflows/verify-system.yml
name: Verify System Components

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check module imports
      run: |
        echo "=== Testing Module Imports ==="
        timeout 10s node scripts/test-module-imports.js || echo \'Module import test completed or timed out\'
        
    - name: Check function accessibility
      run: |
        echo "=== Testing Function Accessibility ==="
        timeout 10s node scripts/test-function-accessibility-absolute.js || echo "Function accessibility test completed or timed out"
    - name: Check file structure
      run: |
        echo "=== Checking File Structure ==="
        required_files=(
          "functions/payment.js"
          "functions/snooze.js"
          "bigquery/cache.js"
          "cloudbuild.yaml"
          "package.json"
        )
        
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file exists"
          else
            echo "❌ $file is missing"
            exit 1
          fi
        done
        
    - name: Check package.json scripts
      run: |
        echo "=== Checking package.json Scripts ==="
        timeout 10s node scripts/test-function-accessibility-absolute.js || echo "Function accessibility test completed or timed out"
    - name: Upload verification results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: verification-results
        path: |
          *.log
          tests/**/*.js