name: Verify System Components
true:
  pull_request:
    branches:
    - main
    - dev
  push:
    branches:
    - main
    - dev
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: 18.x
    - name: Install dependencies
      run: npm ci
    - name: Check module imports
      run: 'echo "=== Testing Module Imports ==="

        timeout 10s node scripts/test-module-imports.js || echo \''Module import test
        completed or timed out\''

        '
    - name: Check function accessibility
      run: 'echo "=== Testing Function Accessibility ==="

        timeout 10s node scripts/test-function-accessibility-absolute.js || echo "Function
        accessibility test completed or timed out"

        '
    - name: Check file structure
      run: "echo \"=== Checking File Structure ===\"\nrequired_files=(\n  \"functions/payment.js\"\
        \n  \"functions/snooze.js\"\n  \"bigquery/cache.js\"\n  \"cloudbuild.yaml\"\
        \n  \"package.json\"\n)\n\nfor file in \"${required_files[@]}\"; do\n  if\
        \ [ -f \"$file\" ]; then\n    echo \"\u2705 $file exists\"\n  else\n    echo\
        \ \"\u274C $file is missing\"\n    exit 1\n  fi\ndone\n"
    - name: Check package.json scripts
      run: 'echo "=== Checking package.json Scripts ==="

        timeout 10s node scripts/test-function-accessibility-absolute.js || echo "Function
        accessibility test completed or timed out"

        '
    - name: Run unified system integration test
      run: 'echo "=== Running Unified System Integration Test ==="

        node tests/unified_system_test.js

        '
    - if: always()
      name: Upload verification results
      uses: actions/upload-artifact@v4
      with:
        name: verification-results
        path: '*.log

          tests/**/*.js'
